export const suggetData = [
  {
    id: 'Dashboard',
    name: 'Dashboard',
    title: 'Dashboard',
    model: 'other',
    route: '/',
  },
  {
    id: 'Logout',
    name: 'Logout',
    title: 'Logout',
    model: 'other',
    route: '/logout',
  },
  {
    id: 'Asset',
    title: 'Media Library',
    name: 'Media Library',
    model: 'other',
    route: '/media-library',
  },
  {
    id: 'Document',
    title: 'Pages',
    name: 'Pages',
    model: 'other',
    route: '/pages',
  },
  {
    id: 'Role',
    title: 'Role',
    name: 'Role',
    model: 'other',
    route: '/role',
  },
  {
    id: 'Profile',
    title: 'Profile',
    name: 'Profile',
    model: 'other',
    route: '/profile',
  },
  {
    id: 'Translations',
    title: 'Translations',
    name: 'Translations',
    model: 'other',
    route: '/translation',
  },
  {
    id: 'Setting',
    title: 'Setting',
    name: 'Setting',
    model: 'other',
    route: '/setting',
  },
  {
    id: 'Report',
    title: 'Report',
    name: 'Report',
    model: 'other',
    route: '/report',
  },
  {
    id: 'Sitemap',
    title: 'Sitemap',
    name: 'Sitemap',
    model: 'other',
    route: '/sitemap',
  },
  {
    id: '404-301',
    title: '404 & 301',
    name: '404 & 301',
    model: 'other',
    route: '/404-301',
  },
  {
    id: 'Indexing',
    title: 'Indexing',
    name: 'Indexing',
    model: 'other',
    route: '/indexing',
  },
  //   {
  //     id: 'Cache',
  //     title: 'Clear Cache',
  //     name: 'Clear Cache',
  //     model: 'other',
  //     route: '/cache',
  //   },
];
